# Generated by Django 5.2 on 2026-05-14 02:13

from django.db import migrations, models
from django.utils.text import slugify
from book_outlet.models import Book

def update_url_if_empty(apps, schme_editor):
    no_urls = Book.objects.filter(url="")
    for book in no_urls:
        book.url = slugify(book.title, allow_unicode=True)
    Book.objects.bulk_update(no_urls,["url"])


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_book_author_book_is_bestselling_alter_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.SlugField(default=''),
        ),
        migrations.RunPython(update_url_if_empty, migrations.RunPython.noop)
    ]
